version: "3.8"

services:
  green:
    container_name: green
    build: .
    ports:
      - "8080:8080"
    environment:
      PROFILE: prod
  blue:
    container_name: blue
    build: .
    ports:
      - "8081:8080"
    environment:
      PROFILE: prod
